# Generated by Django 3.2.5 on 2023-01-16 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_featured_image'),
        ('projects', '0003_project_owner'),
    ]

    operations = [
    ]
